### ISSUE TITLE
layout doesn't seem to work?

### ISSUE THREAD

**Issue by TLINDEN** [gryphonshafer/Mojo-Plugin-Toolkit#2]
Hi,

I've got the following setup:

```
app->defaults(layout => 'main', handler => 'tt');
get '/' => sub { my $c = shift; $c->render(template => 'foo'); }
```

Plugin instantiation is the same as in the docs.

The problem is that it renders foo.html.tt first and main.html.tt _afterwards_
- Tom

**Comment by gryphonshafer** [comment]
Greetings Tom. Thanks for the bug report. Can you include a simplified full example that includes the TT of foo and main and the controller? I'll try to repro on my side in an hour or two. Thanks.

**Comment by TLINDEN** [comment]
https://gist.github.com/TLINDEN/e42ae0c6c13d8894ba07

Structure:
    ttapp.pl
    templates/foo.html.tt
    templates/layouts/main.html.tt

I run it with:
    plackup -r ttapp.pl

OUTPUT is what I get when I call it with the url http://localhost:5000/foo/blah

**Comment by gryphonshafer** [comment]
I wasn't able to reproduce what you have in OUTPUT. Using the exact files you provided, I end up getting as output the wrapper but nothing of the foo template. I tried with packup, morbo, and hypnotoad, but I got the same results.

To fix not seeing the foo template content, you can reference "content" off the controller in the wrapper/layout template. (`[% c.content %]`). I therefore just published a patch (fa40f3c) that copies `c.content` into `content` at the TT layer.

Alternatively to using "layout" in `app->defaults`, you can also use a "WRAPPER" in the TT `config` setting; however, you'll still need to reference the "content" off the controller in the wrapper/layout template.

Note that you can remove the entire `settings` section of the `plugin()` call since the values you have there are all defaults. You can also remove `EVAL_PERL => 0` because that's the default.

**Comment by TLINDEN** [comment]
> I wasn't able to reproduce what you have in OUTPUT.
> Using the exact files you provided, I end up getting as
> output the wrapper but nothing of the foo template. 

Well, the foo template actually works, it renders whatever I place in the url after foo/. But it's rendered before the layout.

> To fix not seeing the foo template content, you can
> reference "content" off the controller in the wrapper/layout
> template. ([% c.content %]). 

Well, there's no wrapper/ directory here, I'm not sure what you mean.
However, I changed `content` to `c.content` in the main.html.tt template. Now I get the foo template rendered even twice: once before the layout and once inside the content placeholder as expected.

I edited the gist accordingly.

btw - it's the same when run via commandline:

```
scip@scip: % perl ttapp.pl  get /foo/huhu
[Thu Dec  3 13:29:43 2015] [debug] GET "/foo/huhu"
[Thu Dec  3 13:29:43 2015] [debug] Routing to a callback
[Thu Dec  3 13:29:43 2015] [debug] 200 OK (0.015805s, 63.271/s)
Our :bar placeholder matched huhu
<!DOCTYPE html>
<html>
  <head><title>MyApp</title></head>
  <body>
    <h1>MyApp</h1>
    Our :bar placeholder matched huhu

  </body>
</html>
```

**Comment by TLINDEN** [comment]
PS: I tried to hunt it down. The problem is, that the template handler gets called twice. During the first run it just renders foo.html.tt without the layout. In the next run, it runs it including the layout but $output still contains the output of the previous run and it gets concatenated.

So, the following patch fixes the issue for me:

```
*** ToolkitRenderer.pm~ Thu Dec  3 16:29:30 2015
--- ToolkitRenderer.pm  Thu Dec  3 16:29:48 2015
***************
*** 24,29 ****
--- 24,30 ----
          my ( $renderer, $controller, $output, $options ) = @_;
          my $inline = $settings->{'settings'}{'inline_template'} || 'inline';

+       $$output = '';
          $template->process(
              ( ( $options->{$inline} ) ? \$options->{$inline} : $renderer->template_name($options) ),
              { %{ $controller->stash }, ( $settings->{'settings'}{'controller'} || 'c' ) => $controller },
```
- Tom

**Comment by gryphonshafer** [comment]
Given that I can't reproduce the issue with fresh libraries, it may be an old dependency that's doing something unexpected. What's your environment like, and what's your Perl version? Are you using anything like local::lib, Carton, or Perlbrew?

Try this:
1. Send me the output of the following command: `perl -MExtUtils::Installed -E '$x=ExtUtils::Installed->new; say $_, q( ), $x->version($_) for $x->modules'`
2. Try installing Perlbrew with a clean library set, and then try to reproduce the problem:

```
curl -skL http://install.perlbrew.pl | /bin/bash
. /opt/perl5/etc/bashrc
echo -e "\n. /opt/perl5/etc/bashrc" >> /etc/bash.bashrc
perlbrew install-cpanm
perlbrew install --thread --notest perl-5.23.0
perlbrew lib create local
perlbrew switch @local
cpanm Mojolicious::Plugin::ToolkitRenderer
```

**Comment by TLINDEN** [comment]
Hi,

I'm already using a perlbrew environment. Here's the module list:

```
Algorithm::Diff 1.1903
Apache::LogFormat::Compiler 0.32
App::Cmd 0.330
AppConfig 1.71
CPAN::Meta::Check 0.012
Capture::Tiny 0.30
Class::Accessor::Lite 0.08
Class::Data::Inheritable 0.08
Class::Inspector 1.28
Class::Load 0.23
Class::Method::Modifiers 2.11
Clone 0.38
Config::Any 0.26
Config::General 2.60
Cookie::Baker 0.06
DBD::SQLite 1.48
DBI 1.634
Dancer2 0.163000
Data::Munge 0.095
Data::OptList 0.109
Devel::CheckCompiler 0.06
Devel::GlobalDestruction 0.13
Devel::StackTrace 2.00
Devel::StackTrace::AsHTML 0.14
Dist::CheckConflicts 0.11
Encode::Locale 1.05
Exception::Class 1.39
Exporter::Tiny 0.042
File::ShareDir 1.102
File::ShareDir::Install 0.10
File::Slurp 9999.19
File::Slurper 0.008
Filesys::Notify::Simple 0.12
Gazelle 0.40
Getopt::Long::Descriptive 0.099
Guard 1.023
HTML::Parser 3.71
HTML::Tagset 3.20
HTTP::Body 1.22
HTTP::Cookies 6.01
HTTP::Date 6.02
HTTP::Headers::Fast 0.19
HTTP::Message 6.11
Hash::Merge::Simple 0.051
Hash::MultiValue 0.16
IO::HTML 1.001
IO::TieCombine 1.005
IPC::Signal 1.00
Import::Into 1.002005
JSON 2.90
LWP::MediaTypes 6.02
List::MoreUtils 0.413
Module::Build 0.4214
Module::Implementation 0.09
Module::Pluggable 5.2
Module::Runtime 0.014
Mojolicious 6.31
Mojolicious::Plugin::ConsoleLogger 0.06
Mojolicious::Plugin::ToolkitRenderer 1.06
Moo 2.000002
MooX::Types::MooseLike 0.29
POSIX::strftime::Compiler 0.41
Package::Stash 0.37
Package::Stash::XS 0.28
Parallel::Prefork 0.17
Params::Util 1.07
Params::Validate 1.21
Perl 5.22.0
Plack 1.0037
Plack::Middleware::FixMissingBodyInRedirect 0.12
Plack::Middleware::RemoveRedundantBody 0.04
Proc::Wait3 0.05
Return::MultiLevel 0.04
Role::Tiny 2.000001
Safe::Isa 1.000005
Scope::Guard 0.21
Server::Starter 0.32
Signal::Mask 0.008
Spiffy 0.46
Stream::Buffered 0.03
String::RewritePrefix 0.007
Sub::Exporter 0.987
Sub::Exporter::Progressive 0.001011
Sub::Install 0.928
Sub::Uplevel 0.25
Template 2.26
Template::Tiny 1.12
Test::Base 0.88
Test::Deep 0.119
Test::Differences 0.63
Test::Exception 0.40
Test::Fatal 0.014
Test::LeakTrace 0.15
Test::MockTime 0.15
Test::Most 0.34
Test::Name::FromLine 0.13
Test::Pod 1.51
Test::Requires 0.10
Test::SharedFork 0.34
Test::TCP 2.14
Test::Time 0.04
Test::Warn 0.30
Test::Warnings 0.021
Test::YAML 1.06
Text::Diff 1.43
Try::Tiny 0.22
URI 1.69
YAML 1.15
```

However, I installed another perl version and inside only M::P::TR and Plack. The problem is not reproducable with this setup.
